name: Postprocess and Deploy

on: 
  workflow_dispatch:


jobs:
  build_pages:
    name: Create JSONL
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      TR_USER: ${{ secrets.TRANSKRIBUS_USER }}
      TR_PW: ${{ secrets.TRANSKRIBUS_PASSWORD  }}
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v3
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: make jsonl
      run: python postprocess.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./html
